# Generated by Django 3.2.12 on 2024-09-08 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_auto_20240908_0455'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todolist',
            old_name='text',
            new_name='task',
        ),
    ]
