# Generated by Django 3.2.12 on 2024-09-08 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0005_auto_20240908_1152'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todolist',
            old_name='task',
            new_name='description',
        ),
    ]
