# Generated by Django 3.2.12 on 2024-09-02 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='url',
            field=models.CharField(default='/', max_length=100),
        ),
    ]
