# Generated by Django 3.2.12 on 2024-09-02 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_application_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='url',
            field=models.CharField(default='', max_length=100),
        ),
    ]
