# Generated by Django 3.2.12 on 2024-09-22 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0004_alter_file_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='File',
        ),
    ]
