# Generated by Django 3.2.12 on 2024-09-22 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0006_file_folder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='folder',
            name='parent_folder',
        ),
        migrations.RemoveField(
            model_name='folder',
            name='user',
        ),
        migrations.DeleteModel(
            name='File',
        ),
        migrations.DeleteModel(
            name='Folder',
        ),
    ]
