# Generated by Django 3.2.12 on 2024-09-22 20:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0008_file_folder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 22, 20, 7, 22, 185756, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='folder',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 22, 20, 7, 22, 184874, tzinfo=utc)),
        ),
    ]
