# Generated by Django 3.2.12 on 2024-09-28 19:02

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('files', '0013_file_folder'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='file',
            unique_together={('name', 'user', 'parent_folder')},
        ),
        migrations.AlterUniqueTogether(
            name='folder',
            unique_together={('name', 'user', 'parent_folder')},
        ),
    ]
