# Generated by Django 3.2.12 on 2024-09-29 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0015_auto_20240929_1554'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='file',
            name='unique_file_name',
        ),
        migrations.RemoveConstraint(
            model_name='folder',
            name='unique_folder_name',
        ),
        migrations.AddConstraint(
            model_name='file',
            constraint=models.UniqueConstraint(fields=('name', 'parent_folder', 'user'), name='unique_file_name'),
        ),
        migrations.AddConstraint(
            model_name='folder',
            constraint=models.UniqueConstraint(fields=('name', 'parent_folder', 'user'), name='unique_folder_name'),
        ),
    ]
